### ISSUE TITLE
gltf example seems to be not loading the microphone anymore

### ISSUE THREAD

**Issue by Palm-Web** [markuslerner/THREE.Interactive#14]
https://dev.markuslerner.com/three.interactive/examples/gltf.html

**Comment by markuslerner** [comment]
Hi @Palm-Web , for me it's loading in Chrome, Safari and Firefox on MacOS, pretty much all in the latest version. Maybe you need to refresh the page so that the latest version is loaded (using three 0.38.0 in the source code).
If it still doesn't work for, please let me know your browser and OS version.
